std_msgs/Header header

# Classification results
string      frame_id
string      bottle_type
float64     score

# Pose with covariance
geometry_msgs/Pose  pose
float64[36]         covariance

# Bounding box size. The center of the bounding box is given by 'pose'
geometry_msgs/Vector3 bbox_size
